const essays = [{
        title: 'low cost airlines',
        prompt: 'The increasing availability of low-cost airlines now lets people travel around the world. Some feel this is a positive development while others think it is negative overall.',
        question: 'Discuss both sides and give your own opinion.',
        link: 'https://tranthanhhthao.github.io/ietls-ouch-low-cost-airlines/',
        essay: ['It is great to get to travel around the world---and low-cost airlines have made this easier. One learns a lot from travel. But should one learn anyhow from discomfort?', 'The greatest advantage of low-cost airline is the least money spent on means of transport. When we focus on the fact that we save money for the trip, we save money for what actually matters; on the plane, we look forward to spending more money on the fun and pleasure after landing. Such as, buying more things, eating more good food; because these things cannot be bought on the plane.', 'But before we get to the destination, does every penny count? Cheap seats of lower comforts and the lack of some services are what low-cost airline offers. Our time on the plane counts as much as time travel at destination. Because it is part of the trip. It can be a really bad start filled with terrible smells. It can ruin everything. Aren\'t time well-spent and valuable experience what make the entire trip worthwhile?', 'To conclude, I see that the disadvantages in cheap seats are many and too much to take. I count every second on the means to get there. They say flighting first-class always be some luxury to experience.']
    }, 
    {
        title: 'sport and learning',
        prompt: 'Some people encourage watching sports as a way of learning about teamwork and strategy, while others believe that one can learn these skills through playing sports.',
        question: 'Discuss both sides and give your own opinion.',
        link: '/sport-and-learning',
        essay: ['In sport, to learn strategy and team-working—some encourage watching sports over playing sports. To me, observing others play sport  would only be a job well-done when one plays some sports themselves and have some deep respect on human dignity. ', 'To consider watching sports and playing sports, let\’s avoid evaluating one thing in the absence of the other.', 'On one hand, watching sports provide a bird\’s eye view—however this view should never be the only view. To optimize the learning of strategy and team-working, effective and thoughtful camera works are needed. Ideally, these works are carried out by heartful and mindful teams of people—who love sport and respect sport players. In reality, I have seen some bad, terrifying, objectifying sport-play on screen with technological-determinism-minded complementary spoke-persons and scripts. These experience (still) strikes me to the core of their inhumane portraits of human trying and of human being actively sporting around a level playing field. ', 'On the other hand, playing sport, players lack something we called a bird\’s eye view or necessary replays for performance analysis. But sport-players know best. Sport is one of the things that we can only get better by actually doing it  so sport-players do know best about the game and everything in-between. When we play sport ourselves, it is possible to see ourselves away from anything objective. ', 'In conclusion, to watch sport is to, at least, show some respect to sport-players; or at best observers, please, not to think of themselves as are wiser and know all-better. Sport is much more than an entertainment. Is it more than counting winning stats, participating in market changes, and driving eye-balls? ']
    }, 
    {
        title: 'ads target kids',
        prompt: 'In some countries, there has been an increase in the number of advertisements which try to persuade children to buy snacks, toys, and other goods. Parents often claim that these ads are unfair.',
        question: 'Discuss both sides and give your own opinion.',
        link: 'https://tranthanhhthao.github.io/ietls-ouch-ads-target-kids/',
        essay: ['In many places, children have become the target of advertising. They are persuaded into buying snacks, toys, and stuffs. Some think the ads are fair-played. Some criticize the business. ', 'One way to look at advertising is that it is inevitably and strategically omnipresent to everyone in this consumer world, children included. As long as the ads are age-appropriate, advertisers don’t need to feel bad for targeting children. Look at the kids being informed, entertained, and given choices. Look at K-pop idols and their endorsements. Everyone seems to win. ', 'Another way to look at advertising is to see concerns of parents. Our children are being manipulated and exploited for profit. They are too young to make well-thought-out decisions. They are too easy to give ads their full attention without being defensive or aware of commercial coercion. Therefore, it is fundamentally unfair and unjust to expose impressionable minds to ruthless advertisement.', 'In conclusion, consumerism leaves no one alone. Personally, I think this is a sad fact that we have to live with in this modern world. I hope we have more ethical advertisers. ']
    }, 
    {
        title: 'imported supermarket',
        prompt: 'Many supermarkets are selling more and more products that are imported from other countries instead of selling food that is locally sourced.',
        question: 'What are the reasons for this? Is this a positive or negative development?',
        link: 'https://tranthanhhthao.github.io/ietls-ouch-imported-supermarket/',
        essay: ['In Vietnam, imported supermarkets are growing in numbers and have become a go-to place for grocery shopping. Here are two major reasons for this development. ', 'First, it is the ingrained distrust in domestic productions. Food from Vietnam is generally regarded as having low quality and mass-produced by the ill ideology of prioritizing low-price. These producers are often proved to risk consumers\' health and harm the environment. Eating this food is widely believed to bring into the body toxic chemicals. So, people turn to imported goods. Contributing to this is the fact that Vietnam has gone through a period of running a retarded closed economy, and when we opened our doors to international markets, people have seen better goods imported.', 'Second, the consumer mentality is to choose the best quality when possible. We see goods from developed countries as having high quality and produced with the latest technology. For example, we don\'t mind spending more money on Australian meat instead of locally sourced meat. There\'s a saying that its price is its quality. Eating and drinking quality products means taking care of one\'s health. We have a culture that tells people to treat themselves with supreme goods to improve well-being. ', 'Overall, this is a positive development because imported supermarkets give people more choices. People can choose health and premium consumer experiences.  ']
    }, 
    {
        title: 'cycling license',
        prompt: 'Some experts say for road safety cyclists should pass a test before being allowed on public roads.',
        question: 'To what extent do you agree or disagree?',
        link: 'https://tranthanhhthao.github.io/ietls-ouch-cycling-license/',
        esssay: ['While some experts are saying that we need a cycling license for better road safety—I think  we don\'t need such an unnecessary rule in Vietnam. Here\'s why. ', 'First, obtaining a cycling license would only be a barrier for everyone. Everyone who wants to ride their bikes on the road would not be able to do it right away. It would take some time to take the test and pass it, much bureaucratic paperwork to ID, and money as well. While in reality, cycling is considered the easiest and cheapest option to travel independently, then, it would suddenly become very inconvenient, especially for people who do not have at hand the time and documentation that are required. ', 'Secondly, we don\'t need to test people on how to ride such a simple vehicle; but rather, by cycling on the road, people have proven enough. Just like nobody is required a license to cross the street, nobody should be required a license to cycle because basic traffic knowledge is quick to learn. ', 'To conclude, requiring a cycling license won\’t work for roads in Vietnam. It would create a barrier for people to get around lawfully and a redundant testing system. How about trying other realistic ways to improve road safety like raising awareness, placing more readable eye-level signs, and reconstructing improper roadways?']
    }, 
    {
        title: 'old age and youth',
        prompt: 'In some places, old age is valued, while in other cultures youth is considered more important.',
        question: 'Discuss both views and give your opinion.',
        link: 'https://tranthanhhthao.github.io/ietls-ouch-old-age-and-youth', 
        essay: ['While elders are paid the utmost respect in places, youth is of the greatest things elsewhere.', 'My culture teaches me to value old age the most. Confucianism emphasizes filial piety. Seeing an old person is like seeing somebody\’s mom or dad. They are of great value because of their lifelong experience and wisdoms. It is culturally unacceptable to wrong old people at any matter. As a culture, we hold in high regard the quality of being traditional and conservative. ', 'But, I feel a bit suffocating at home every now and then. And I find myself attracted to youth cultures elsewhere. ', 'Youth in America seems excitingly different. They are great even when they rebel without a cause. Their decisions are not underestimated because they lack real life experience. They can decide everything for themselves. They of course can make bad choices—and that is okay—as long as they have the adventure and the self-discovery. It seems that young people are encouraged to be brand new, to break old patterns and think outside the box. Which probably because the American culture admires creativity and resistance much. ', 'Personally, I\’m not a fan of Confucianism in my culture. I do respect old people but to an extent. I don\’t like conservatives, who are mostly old. ']
    }, {
        title: 'reading for children',
        prompt: 'Some people believe that engaging in an active pastime does more to develop childrens\’ life skills than time spent reading.',
        question: 'To what extent do you agree or disagree?',
        link: 'https://tranthanhhthao.github.io/ietls-ouch-reading-for-children',
        essay: ['Many people would rather children spending time doing other things than reading. They consider reading not an active pastime and not very helpful developing life skills at a young age. I disagree—I think reading is essential to growth.', 'First, reading requires and strengthens children\’s ability to concentrate and self-discipline—it is not an passive thing to do. While reading, they need to constantly reflect on what they have known and read. After reading, they often arrive at an intellectual discussion with the writers while coming to senses with their understanding. In short, reading is a form of communicating attentively. ', 'Secondly, reading exercises the brain and helps children improve language skills. It allows them to comprehend the meaning of language, literacy, and social skills. It also gets them ready for academic life. In other words, the benefits of reading are many and are for children as well. Therefore, it is right to encourage children to read in their free time. ', 'To conclude, it\’s actually great to allow children to read while letting them set up their own schedules. Remember to pick a reading list that suits their reading-level so they can feel engaging and have a chance to challenge themselves to level up. ']
    }, {
        title: 'fresh water',
        prompt: 'Some people think that the government should strictly control the supply of fresh water, as it is a limited resource, while others think it should not be regulated.',
        question: 'Discuss both sides and give your opinion.',
        link: 'https://tranthanhhthao.github.io/ielts-ouch-fresh-water',
        essay: ['As for fresh water is a limited resources, some want the government to control access while others oppose the regulation. ', 'On one hand, government control should be about making sure all people fairly share the resource, not about granting privileges to few. Ideally, the government should publicly and justly fine corporates and individuals who contaminate the water supplies, quickly clean up polluted reservoirs, strategically forge fair competitions between stakeholders who supply fresh water, effectively call people into the awareness that we have fresh water in limited amount, and frequently encourage people to conserve water. But in reality, the Vietnamese government notoriously often waste time and money while being an authoritarian. It\’s simply wrong to leave our future entirely to this government\’s hand. ', 'On the other hand, no amount of tax and restrictions can properly bring the right environmental awareness. People should let to self-regulate their fresh water usage. For example, supply companies can let people purchase environmental plans that work for them. And when people exceed their daily planned usage, they will have to pay extra fee to use more or there will be no more available fresh water that day. This way, the market and private businesses practically determine fresh water access and consumption without any government regulation. ', 'Because we don\’t want a future of not having enough fresh water for everyone, it\’s important that we purposefully track our usage and plan ahead to go green. Yet, the government should take action to protect our ecosystem—but not necessarily be the first to lead.']
    }, {
        title: 'wildlife conservation',
        prompt: 'Some people claim that too much focus and resources have been spent to protect wild animals and birds.',
        question: 'To what extent do you agree or disagree?',
        link: 'https://tranthanhhthao.github.io/ietls-ouch-wildlife-conservation',
        essay: ['Some say that wildlife conservation is overrated and we are wasting money. I don’t think so. It might be true elsewhere, but not in Vietnam. ', 'When I visited the Saigon Zoo this year, the animals there lived in dirty small cages and seemed inactive and underweight. It was clear that there was not enough focus and resources spent on wildlife conservation. The poor living condition of these animals seemed to limit them naturally, despite being able to keep them alive. Critically, I saw that we never appreciated wildlife enough to thoughtfully provide healthy habitats.', 'But the zoo appears to be doing fine commercially because it is the only zoo in the city. We should openly and publicly criticize their business and demand them to improve. The zoo did not send the message that the animals are well protected. Instead, the zoo showcased idle lives and terrible smells.', 'It\'s important that wildlife conservation teach us to live sustainably with other species. But to this reality of wild animals and birds in Vietnam, our standard for protecting them is fundamentally wrong-headed and actually damaging our ecosystem.']
    }, {
        title: 'learn to cope with change',
        prompt: 'The best curriculum is not one based on a static body of knowledge, but one which teaches students to cope with change.',
        question: 'To what extent do you agree or disagree?',
        link: 'https://tranthanhhthao.github.io/ietls-ouch-cope-with-change',
        essay: ['Many say the only constant in life is change. So to learn to cope with change is to learn to best prepare while in school.', 'Being able to adapt to changes is vital because life these days is fast-paced and full of trends come and go. What we learn today can possibly be outdated very soon. Our knowledge and skillsets in all areas need to be updated regularly with time. Say, if we can\’t keep up for whatever reason, we\’ll prone to feel lagged behind.', 'Students should know their bests when being overwhelmed and overloaded. New changes can just be anything, whether it\’s a life event, an unexpected illness, a life-changing opportunity, a new programming language, a failure, a new science discovery, a new trending hairstyle, a supernatural strike, or even a pandemic. Whatever may come, it\’s important that students are eager to update and apply their knowledge to all aspect in life. Never to be static and content with what they have read in textbooks. ', 'To conclude, may students learn their ways to be able to recover, reboot, and restart when life goes through ups and downs. In our life-long learning and working, get ready to learn more on the job.']
    }, {
        title: 'city life',
        prompt: 'A rise in the standard of living in a country often only seems to benefit cities rather than rural areas.', 
        question: 'What problems can this cause? How might these problems be reduced?', 
        link: 'https://tranthanhhthao.github.io/ietls-ouch-city-life',
        essay: ['As our living standard gets higher, unlike rural areas, cities indicate the promise of fulfillment where modern needs and demands are commonly voiced and heard. ', 'One problem occurs when large numbers of people move to cities is overcrowding. There is not enough resources for everyone. Shortages of housing and employment lead people to slums and poverty. The solution is to promote economic development related to building new residences and job creation. So in other words, city life is about better houses and better jobs. ', 'Another problem followed is environmental degradation. Firstly, concentrated energy use brings about air pollution. Secondly, trash landfills becoming full very quickly every day cause land pollution. Thirdly, pollution contaminates water supplies. Ultimately, congested cities kill the ecosystem and individuals\’ health. Therefore, going green is the solution, which calls for awareness and healthy lifestyles.', 'Urbanization is happening everywhere at great speed. Despite many problems, city life remains incredibly attractive. It is where people robustly seek higher lives because it\’s possible. ']
    }, {
        title: 'patriotism',
        prompt: 'Some people say patriotism causes problems and is negative overall. Others feel that it is beneficial for society at large.',
        question: 'Do the advantages of patriotism outweigh its disadvantages?',
        link: 'https://tranthanhhthao.github.io/ietls-ouch-patriotism',
        essay: ['It\’s important to note, patriotism and the love for humanity can be two very different things. Patriotism can just mean a blind faith in an authoritarian government. Yet, patriotism becomes beneficial to stabilize and prolong a regime. ', 'The advantages of patriotism come with superior status and enormous pride for the individual. One can feel self-righteous aligning oneself with every standard set out and promoted by the government. One irrationally gives the government quantitative support. So for an authoritarian government like Vietnam, the advantages for a patriot individual are called to everyone\’s attention to keep the regime strong.', 'The biggest disadvantage from blindly love the country is that one refuses to doubt and challenge the government. But with a truth that the government can do wrong and oppress individual freedom, one may defend lies and aim to silent opposing views unconditionally. This leads to another disadvantage which is one becomes the enemy of the oppressed, one becomes the oppressor. One is very likely to unreasonably justify violent conducts as an act of patriotism. ', 'In short, patriotism can easily become toxic because its disadvantages are too damaging to justice for all people.']
    }, {
        title: 'moving away',
        prompt: 'More and more people today are moving away from where their friends and family live.', 
        question: 'Do the advantages of this trend outweigh the disadvantages?',
        link: 'https://tranthanhhthao.github.io/ietls-ouch-moving-away',
        essay: ['If you want live far-off from your friends and family, you should be able to. Many people now follow this trend. It\’s about living your own way.', 'The advantages of moving to a complete new neighborhood are all about a liberated new start. You can start living a lifestyle that is more aligned with your beliefs, ideals, and identity. This new lifestyle can be encouraged or simply possible in this new place. Don\’t worry much, you don\’t have to feel so lonely when you can call home and video chat with anyone anytime.', 'The biggest disadvantage is that, at first, you have no one to take care of you but yourself. You have to set up your own place by yourself. You have to introduce yourself to everyone to build new relationships. You\’re of a new self all alone without your support system. Another disadvantage is that you are very vulnerable going through life knowing no one to trust. You become a prey or an easy target of many evil schemes. ', 'Anyways, it\’s up to you to decide if you really want the advantages. For me, I wanted a new start so once I moved to Texas alone to study despite any disadvantage might come. I wanted an independent life in America where my beliefs and attitudes are on display without fear. Being able to freely express myself made me feel very seen. And that seemed to be what kept me through many stressful nights I cried myself to sleep. ']
    }, {
        title: 'housing shortages',
        prompt: 'There are severe social consequences to housing shortages in cities and only the government can solve these problems.',
        question: 'To what extent do you agree or disagree?', 
        link: 'https://tranthanhhthao.github.io/ietls-ouch-housing-shortages',
        essay: ['If the government become all-powerful and is the only one to solve housing shortages for city populations, then many lives are lived at the expense of personal freedom. We should not let a powerful few decide urban governance for all people. ', 'Housing shortages happen when urban governance works poorly. In urban governance, the government is the biggest and most visible actor, but not the only one. Adequate places to live for city people are also determined by the market and private businesses. To address housing problems sufficiently, the government need to listen and encourage people to participate in civic engagement. ', 'Solutions to housing shortages such as planning and building new residences for people to live in, expanding and upgrading public transportation and highways for people to commute while living nearby the city, need the government to play the strategic role of establishing relations between stakeholders. But people should always let to decide for themselves whether the solutions work for them or not. People should have the right to protest and be able to vote for governors that serve them well. People should be able to write to their representatives and feel free to voice and discuss their problems and prospect solutions in everyday life, online and offline. ', 'Never let the government be the sole problem-solver to such severe experience of urban life. Not to be all-powerful is for the government to be just and do their job properly serving all people. ']
    }, 
    
    

];

export default essays;
